### PR TITLE
some spelling changes

### PR DESCRIPTION
**Pull request by carryforward**
was reading through trying to understand your sibyl resistance and typos kept jumping out at me.  Are Fobs hard to get?  Do they require sacrifice of safecoin, etc.  you seem to still be sibyl susceptible is Fobs are trivial to generate.

### CODE REVIEW

**Comment by dirvine** [comment]
On Sat, Jan 24, 2015 at 1:24 AM, Brian Deery <notifications@github.com>
wrote:

> Are Fobs hard to get?


Yes they require to be within 2 or less common leading bits and average the
network rank. This part is crucial and we do not explain it well, basically
we force even distribution of the keys


-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by carryforward** [comment]
I know this is the wrong forum, but there is a little bit of dialog started already.  My project has a DHT to secure, and I am worried about sibyl resistance.  I was pointed to this document as an example where we can take some cues from your method to protect against sibyls.  I like how it takes a group to make decisons, and groups deal with other gropus.  probalistically, when I join a group it will be randomly spread out. I see where this spreads out honest nodes.

If I am an attacker, and there is one piece of data which I want to attack, I can create a bunch of sibyls around that data.  If creating fobs is easy, an attacker can grind to find many ids with the 2 leading bits being in the group which I want to attack.  Eventually, I will control a majority of users in that group.  Once I do that, I can lie and say the data doesn't exist anymore.  

Does the network rank allow a minority to flag a majority in the group as problematic?  if this is the case, then it may be a bigger problem.

I really want to have a sibyl resistant DHT, but I don't see how it will work out.  is there another document to read about this?

**Comment by dirvine** [comment]
On Mon, Jan 26, 2015 at 7:11 PM, Brian Deery <notifications@github.com>
wrote:

> I can create a bunch of sibyls around that data. If creating fobs is easy


This is the part to be focussed on. If you grab our address_space_tool in
common you can adjust group sizes and quorum to figure out the security via
group consensus and then it will become more clear I think. If you assume
no matter how easy/hard it is to create keys etc. then imagine it is easy
and run this tool.

In terms of rank the tool takes a very simple approach and does not allow
two rank 0 nodes in any group, but immediately a nodes rank is non zero in
the tool (so conservative to say the least). It also assumes all attacks
are the attacker only and no other attackers or nodes are joining, this
gives the attack a chance and therefore e can measure it.  There is a
probability of attack equation if it helps (you could code it up in
sagemaths if you wanted (allow much faster calculations of security via
group consensus) we have not done it yet but if you did then please let us
know.


-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by dirvine** [comment]
Thanks for the typo fixes, I pulled this together pretty quickly to describe a sentinel approach to consensus, cheers again nice one

**Pull request merged**
